extends Node

const DEFAULT_GET_STATE_WAIT_TIME: float = 1.0
const THRESHOLD_OF_SECOND_ROUNDING: float = 0.85
const DELAYS_LIST_SIZE: int = 10
const TICKS_WITHOUT_SYNCHRONIZATION: int = 3
const BUSY_HTTP_STATUSES: Array[int] = [HTTPClient.STATUS_CONNECTING, HTTPClient.STATUS_REQUESTING]
const DEFAULT_ACTION_SPEED: float = 0.5
