name: Godot testing

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: croconut/godot-tester@master
      with:
        version: "4.0.3"
        release_type: "stable"
        test-dir: "res://tests"
